### ISSUE TITLE
Incomplete dependencies to Eclipse OCL

### ISSUE THREAD

**Issue by Entenwilli** [DataFlowAnalysis/product#6]
The project has some runtime editor dependencies to Eclipse OCL, which are not marked as dependencies for the repository. The required runtime dependencies for the pddc editor are either contained in the `org.eclipse.ocl.build.feature.group` or `org.eclipse.ocl.examples.feature.group`.

We need to investigate how to fix the missing dependencies. The current workaround is to install both features manually

**Comment by Entenwilli** [comment]
From last week's meeting, it seems `org.eclipse.ocl.examples.feature.group` is the missing feature

**Comment by Nicolas-Boltz** [comment]
I was in there already and the current product on the updatesite has it installed.
I somehow pushed an old version of the feature.xml when removing indirections?!?! I will fix that later today
